// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc0.NewBot;
    
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController robotDriveleftdrive;
    public static SpeedController robotDriverightdrive;
    public static RobotDrive robotDriveRobotDrive21;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        robotDriveleftdrive = new Victor(1, 1);
	LiveWindow.addActuator("RobotDrive", "leftdrive", (Victor) robotDriveleftdrive);
        
        robotDriverightdrive = new Victor(1, 2);
	LiveWindow.addActuator("RobotDrive", "rightdrive", (Victor) robotDriverightdrive);
        
        robotDriveRobotDrive21 = new RobotDrive(robotDriveleftdrive, robotDriverightdrive);
	
        robotDriveRobotDrive21.setSafetyEnabled(true);
        robotDriveRobotDrive21.setExpiration(0.1);
        robotDriveRobotDrive21.setSensitivity(0.5);
        robotDriveRobotDrive21.setMaxOutput(1.0);
        
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
